baseUrl:
  # apiOps: 'https://api.dev2.setel.my'
  apiOps: 'https://api.dev.logistika.com.my/api/receiver'


appUrl:
  webcommon: 'https://web-bundles.setel.my/dev/web-common/latest'
  webdebug: 'https://web-bundles.setel.my/dev/web-debug/latest'
